[package]
name = "maximumadhd/tags"
description = "Tags - A less verbose version of the CollectionService with support for binding to Troves and simple add/remove wrappers."
version = "1.0.1"
license = "MIT"
authors = ["MaximumADHD"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Trove = "sleitnick/trove@1.5.1"
Signal = "sleitnick/signal@2.0.3"
RunContext = "maximumadhd/run-context@^1"