[package]
name = "maximumadhd/roblox-utils"
description = "A collection of utilities for Roblox development."
version = "1.0.0"
license = "MIT"
authors = ["MaximumADHD"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
React = "roblox/react@17.3.11"
Trove = "sleitnick/trove@1.5.1"
Signal = "sleitnick/signal@2.0.3"
Squash = "data-oriented-house/squash@4.1.0"
ReactRoblox = "roblox/react-roblox@17.3.11"
ReactGlobals = "roblox/react-globals@17.3.11"
PromiseBase = "evaera/promise@4.0.0"