[package]
name = "maximumadhd/roblox-utils"
description = "A collection of utilities for Roblox development."
version = "1.0.0"
license = "MIT"
authors = ["MaximumADHD"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Trove = "sleitnick/trove@1.5.1"
Signal = "sleitnick/signal@2.0.3"
PromiseBase = "evaera/promise@4.0.0"