[package]
name = "maximumadhd/guid"
description = "Guid - A module for generating GUIDs and storing them in buffers."
version = "1.0.0"
license = "MIT"
authors = ["MaximumADHD"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@^1"
Network = "maximumadhd/network@^1"
Promise = "maximumadhd/promise-typed@^1"
RunContext = "maximumadhd/run-context@^1"