[package]
name = "maximumadhd/guid"
description = "Guid - A module for generating GUIDs and storing them in buffers."
version = "1.0.1"
license = "MIT"
authors = ["MaximumADHD"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"