[package]
name = "maximumadhd/octree"
description = "Octree - A spatial partitioning data structure. Originally written by Quenty, updated to have type annotations."
version = "1.0.0"
license = "MIT"
authors = ["MaximumADHD"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"