[package]
name = "maximumadhd/crunch-table"
description = "CrunchTable - A shallow typechecked wrapper around Squash that allows you to define a data layout without needing to worry about the underlying serdes functions."
version = "1.1.2"
license = "MIT"
authors = ["MaximumADHD"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Squash = "data-oriented-house/squash@4.1.0"
