[package]
name = "maximumadhd/easy-store"
description = "EasyStore - A simple, typechecked, cross-context DataStore module for Roblox games. Can be used in server, client, and edit mode contexts."
version = "1.0.1"
license = "MIT"
authors = ["MaximumADHD"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Trove = "sleitnick/trove@1.5.1"
Signal = "sleitnick/signal@2.0.3"
Network = "maximumadhd/network@1.0.0"
Promise = "maximumadhd/promise-typed@1.0.0"
DeltaTable = "maximumadhd/delta-table@1.0.0"
RunContext = "maximumadhd/run-context@1.0.0"