[package]
name = "maximumadhd/delta-table"
description = "DeltaTable - A lightweight module for deep-diffing and patching Lua tables."
version = "1.0.1"
license = "MIT"
authors = ["MaximumADHD"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
