[package]
name = "maximumadhd/stack-modifier"
description = "StackModifier - A module for handling multiple concurrent property modifiers on a single target."
version = "1.0.0"
license = "MIT"
authors = ["MaximumADHD"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
RunContext = "maximumadhd/run-context@1.0.0"
AVLTree = "maximumadhd/avl-tree@1.0.0"
Trove = "sleitnick/trove@1.5.1"
Tags = "maximumadhd/tags@1.0.1"