[package]
name = "maximumadhd/marketplace"
description = "Marketplace - An all-in-one lightweight solution for handling and mocking in-game purchases."
version = "1.0.0"
license = "MIT"
authors = ["MaximumADHD"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@^1"
Network = "maximumadhd/network@^1"
Promise = "maximumadhd/promise-typed@^1"
RunContext = "maximumadhd/run-context@^1"