[package]
name = "maximumadhd/promise-typed"
description = "A lazily typed wrapper around evaera's Promise library."
version = "1.0.0"
license = "MIT"
authors = ["MaximumADHD"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
PromiseBase = "evaera/promise@4.0.0"